# Eureka客户端
spring:
    application:
        name: client
server:
    port: 8081
eureka:
#  instance:
#    hostname: client
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/